package com.rule

import com.javainuse.model.Student

rule "Branch Validation"
	when 
		stuObject: Student(stuObject.getBranch() != "")
	then
		stuObject.setBranchValidationFlag("True");
	end
rule "Sapid Validation"
	when 
		stuObject: Student(stuObject.getSapId() != "" && 
						   stuObject.getSapId().matches(".*\\d.*") &&
						   stuObject.getSapId().length() == 9)
	then
		stuObject.setSapidValidationFlag("True");
	end	
rule "Roll No Validation"
	when 
		stuObject: Student(stuObject.getRollNo() != "" &&
						   stuObject.getRollNo().indexOf('R') == 0 &&
						   stuObject.getRollNo().length() == 10)
	then
		stuObject.setRollnoValidationFlag("True");
	end
rule "Batch Validation"
	when 
		stuObject: Student(stuObject.getBatch() != "" && 
						   stuObject.getBatch().matches(".*\\d.*"))
	then
		stuObject.setBatchValidationFlag("True");
	end
rule "Name Validation"
	when 
		stuObject: Student(stuObject.getName() != "" && 
						   !stuObject.getName().matches(".*\\d.*"))
	then
		stuObject.setNameValidationFlag("True");
	end
rule "CGPA Validation"
	when 
		stuObject: Student(stuObject.getCgpa() != "")
	then
		stuObject.setCgpaValidationFlag("True");
	end